-- DB2.md §2: content revisions for chain-grand-palace-heritage lore nodes.
-- gp-2/gp-3 explicitly carry over as-is (no factual edit requested) — not touched.
-- Applied to live Supabase via MCP apply_migration 2026-07-15; this file is the repo record.

UPDATE lore_nodes SET
  content_th = 'บนฐานไพทีแห่งนี้ประดิษฐานอาคารสามหลังจากสามรัชสมัย มีรูปแบบสถาปัตยกรรมแตกต่างกันโดยสิ้นเชิง ได้แก่ พระศรีรัตนเจดีย์ทรงลังกาบุทองคำ พระมณฑปยอดแหลมซึ่งใช้เป็นที่เก็บพระไตรปิฎก และปราสาทพระเทพบิดร ปราสาทจตุรมุขที่สร้างขึ้นในรัชสมัยพระบาทสมเด็จพระจอมเกล้าเจ้าอยู่หัวเมื่อ พ.ศ. 2398 เดิมมีพระราชประสงค์ให้เป็นที่ประดิษฐานพระพุทธมหามณีรัตนปฏิมากร แต่ด้วยขนาดที่คับแคบเกินไป จึงเปลี่ยนวัตถุประสงค์ในการปฏิสังขรณ์เมื่อ พ.ศ. 2446 ให้เป็นที่ประดิษฐานพระบรมรูปหล่อสมเด็จพระบูรพมหากษัตริยาธิราชแห่งราชวงศ์จักรี เปิดให้ประชาชนเข้าถวายบังคมได้เพียงปีละครั้งในวันจักรี (6 เมษายน) วัดพระศรีรัตนศาสดารามเป็นวัดหลวงเพียงแห่งเดียวในประเทศไทยที่ไม่มีพระภิกษุจำพรรษา เนื่องจากพระบาทสมเด็จพระพุทธยอดฟ้าจุฬาโลกมหาราชทรงมีพระราชประสงค์ให้เป็นเพียงที่ประดิษฐานพระพุทธรูปคู่บ้านคู่เมืองเท่านั้น',
  content_en = 'The upper terrace holds three structures from three different reigns, each in a distinct architectural style: the gold-clad, Ceylonese-style Phra Sri Rattana Chedi; the spired Phra Mondop, built to house the Tripitaka; and Prasat Phra Thep Bidon, a four-porched pavilion built under King Mongkut (Rama IV) in 1855. It was originally intended to enshrine the Emerald Buddha, but proved too small for the purpose; following renovation in 1903 it was rededicated as the Royal Pantheon, housing bronze statues of the Chakri dynasty''s kings, opened to the public only once a year on Chakri Memorial Day (6 April). Wat Phra Kaew remains the only royal temple in Thailand with no resident monks, as King Rama I intended it solely as the shrine of the kingdom''s most sacred image.'
WHERE id = 'lore-gp-1';

UPDATE lore_nodes SET
  content_th = 'อาคารรัษฎากรพิพัฒน์เดิมสร้างขึ้นในรัชสมัยพระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัวราวทศวรรษ 2410 เพื่อใช้เป็นที่ทำการกรมพระคลังและกรมศุลกากร ต่อมาใน พ.ศ. 2546 สมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถ ทรงขอพระราชทานพระบรมราชานุญาตใช้อาคารซึ่งว่างเปล่าอยู่ในขณะนั้นเพื่อจัดตั้งเป็นพิพิธภัณฑ์ผ้า ภายหลังการบูรณะครั้งใหญ่ พิพิธภัณฑ์ผ้าในสมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถ จึงเปิดให้เข้าชมอย่างเป็นทางการในเดือนพฤษภาคม พ.ศ. 2555 จัดแสดงประวัติศาสตร์สิ่งทอไทยและงานหัตถศิลป์การทอผ้าจากทั่วประเทศ อาคารหลังนี้จึงเปลี่ยนบทบาทจากที่ทำการราชการด้านการคลัง มาเป็นสถานที่รักษามรดกหัตถศิลป์ของแผ่นดิน',
  content_en = 'The Ratsadakorn-bhibhathana Building was originally constructed in the 1870s, in the reign of King Chulalongkorn (Rama V), to house the Royal Treasury and Customs Departments. In 2003, Queen Sirikit requested royal permission to repurpose the then-vacant building as a textile museum. Following extensive renovation, the Queen Sirikit Museum of Textiles officially opened in May 2012, exhibiting the history of Thai textiles and weaving craftsmanship from across the country. The building''s role has thus shifted — from a government finance office to a permanent home for the kingdom''s textile heritage.'
WHERE id = 'lore-gp-4';

UPDATE lore_nodes SET
  content_th = 'ใน พ.ศ. 2522 พระบาทสมเด็จพระบรมชนกาธิเบศร มหาภูมิพลอดุลยเดชมหาราช บรมนาถบพิตร ทรงพระกรุณาโปรดเกล้าฯ ให้สมเด็จพระกนิษฐาธิราชเจ้า กรมสมเด็จพระเทพรัตนราชสุดาฯ สยามบรมราชกุมารี ทรงเป็นประธานกรรมการอำนวยการปฏิสังขรณ์วัดพระศรีรัตนศาสดารามและพระบรมมหาราชวัง เนื่องในโอกาสสมโภชกรุงรัตนโกสินทร์ครบ 200 ปี พิพิธภัณฑ์วัดพระศรีรัตนศาสดารามจึงเปิดให้เข้าชมอย่างเป็นทางการเมื่อวันที่ 7 พฤษภาคม พ.ศ. 2525 และดำเนินการต่อเนื่องมากว่าสี่ทศวรรษ ก่อนปิดปรับปรุงตั้งแต่วันที่ 5 สิงหาคม พ.ศ. 2567 จนถึงปัจจุบัน ยังไม่มีกำหนดเปิดใหม่',
  content_en = 'The restoration effort began in 1979, when King Bhumibol Adulyadej appointed HRH Princess Maha Chakri Sirindhorn to chair the restoration committee for Wat Phra Kaew and the Grand Palace, ahead of the 200th anniversary of the founding of Bangkok. The Museum of Wat Phra Kaew opened as a result on 7 May 1982, and operated continuously for over four decades before closing for renovation on 5 August 2024 — it remains closed, with no announced reopening date.'
WHERE id = 'lore-gp-5';

UPDATE lore_nodes SET
  content_th = 'หมู่พระมหามณเฑียรเป็นหมู่พระที่นั่งแรกที่สร้างขึ้นในรัชสมัยพระบาทสมเด็จพระพุทธยอดฟ้าจุฬาโลกมหาราชเมื่อ พ.ศ. 2325 ประกอบด้วยพระที่นั่งและหอเชื่อมต่อเนื่องกันรวม 7 องค์ พระที่นั่งจักรพรรดิพิมานเป็นที่ประทับส่วนพระองค์ของพระมหากษัตริย์ตั้งแต่รัชกาลที่ 1 ถึงรัชกาลที่ 3 และยังคงใช้เป็นสถานที่ประกอบพระราชพิธีสำคัญ อาทิ การบรรทมเป็นสัญลักษณ์ในพระราชพิธีบรมราชาภิเษกสืบมาจนถึงปัจจุบัน พระที่นั่งไพศาลทักษิณเป็นที่ประดิษฐานพระสยามเทวาธิราช เทพารักษ์ผู้พิทักษ์แผ่นดินสยาม ส่วนพระที่นั่งอมรินทรวินิจฉัยใช้เป็นท้องพระโรงสำหรับออกว่าราชการและประกอบพระราชพิธี',
  content_en = 'The Grand Mahamontien Residential Group was the first set of royal residences built under King Rama I in 1782, comprising seven interconnected halls and pavilions. Chakraphat Phiman Hall served as the private bedchamber of the reigning king from Rama I through Rama III, and remains part of the coronation ceremony to this day, in which the new king symbolically spends a night there. Phaisan Thaksin Hall enshrines the Phra Siam Devadhiraj, the guardian deity of the kingdom, while Amarin Winitchai Hall serves as the throne hall for royal audiences and ceremonies.'
WHERE id = 'lore-gp-6';

-- DB2.md §3: new standalone Rangsit lore, near the existing TU Rangsit campus support
-- node (node-tu-rangsit, 14.0716,100.6072) — spread out slightly so they don't stack.
INSERT INTO lore_nodes (id, name_th, name_en, lat, lng, radius_m, lore_pts, content_type, content_th, content_en, chain_id, chain_part, district_id, review_status)
VALUES
('lore-rangsit-canal', 'คลองรังสิตประยูรศักดิ์', 'Rangsit Canal', 14.0680, 100.6040, 100, 25, 'text',
 'คลองรังสิตประยูรศักดิ์เริ่มขุดเมื่อ พ.ศ. 2433 ในรัชสมัยพระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัว ดำเนินการโดยบริษัท ขุดคลองแลคูนาสยาม จำกัด นับเป็นคลองสายหลักของโครงการพัฒนาที่ดินขนาดใหญ่โครงการแรกของประเทศไทย เชื่อมแม่น้ำเจ้าพระยากับแม่น้ำนครนายก เปิดพื้นที่รกร้างระหว่างสองแม่น้ำให้กลายเป็นที่ดินทำกินได้กว่าล้านไร่',
 'Rangsit Canal (Khlong Rangsit Prayurasakdi) began excavation in 1890 under King Chulalongkorn (Rama V), carried out by the Siam Canal, Land, and Irrigation Company. It formed the main artery of Thailand''s first large-scale land development project, linking the Chao Phraya and Nakhon Nayok rivers and opening over a million rai of previously unused land between them for cultivation.',
 NULL, NULL, 'rangsit', 'pending'),
('lore-rangsit-agriculture', 'เกษตรกรรมแห่งรังสิต', 'Rangsit Agricultural Development', 14.0740, 100.6090, 100, 25, 'text',
 'การขุดคลองรังสิตทำให้เกิดโครงข่ายคลองซอยกว่า 100 สาย ระบายน้ำและชลประทานพื้นที่ราบลุ่มภาคกลางตอนล่าง เปลี่ยนทุ่งร้างให้กลายเป็นแหล่งปลูกข้าวที่สำคัญที่สุดแห่งหนึ่งของสยาม ดึงดูดชาวนาจากทั่วประเทศให้อพยพเข้ามาจับจองที่ดิน วางรากฐานให้รังสิตกลายเป็นศูนย์กลางเกษตรกรรมของจังหวัดปทุมธานีมาจนถึงปัจจุบัน',
 'The Rangsit Canal project spawned a network of over 100 branch canals, draining and irrigating the lower central plain and turning previously idle fields into one of Siam''s most important rice-growing regions. It drew farmers from across the country to claim land, laying the foundation for Rangsit''s continued role as the agricultural center of Pathum Thani province.',
 NULL, NULL, 'rangsit', 'pending'),
('lore-rangsit-name-origin', 'ที่มาของชื่อ "รังสิต"', 'The Name "Rangsit"', 14.0700, 100.6110, 100, 25, 'text',
 'ชื่อ "รังสิต" มาจากพระนามของพระเจ้าลูกยาเธอ พระองค์เจ้ารังสิตประยูรศักดิ์ พระราชโอรสองค์ที่ 58 ในพระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัว ประสูติแต่เจ้าจอมมารดาหม่อมราชวงศ์เนื่อง สนิทวงศ์ คลองและพื้นที่โดยรอบจึงได้รับพระราชทานนามตามพระนามของพระองค์ ภายหลังทรงเลื่อนกรมขึ้นเป็นสมเด็จพระเจ้าบรมวงศ์เธอ กรมพระยาชัยนาทนเรนทร ทรงมีบทบาทสำคัญด้านการแพทย์และสาธารณสุขของประเทศในเวลาต่อมา',
 'The name "Rangsit" derives from Prince Rangsit Prayurasakdi, the 58th son of King Chulalongkorn (Rama V), born to Chao Chom Manda M.R. Nueang Sanitwong. The canal and surrounding area were named in his honor. He was later elevated in rank to Prince Chainat Narenthorn (กรมพระยาชัยนาทนเรนทร) — the same "Prince of Chainat" — and went on to play a major role in Thailand''s medicine and public health institutions.',
 NULL, NULL, 'rangsit', 'pending')
ON CONFLICT (id) DO NOTHING;
