-- Systematic Verification Process for support_nodes + watchtowers coordinates.
-- Every point starts 'pending' until a reviewer physically/manually confirms
-- it sits on public land, or flags it as landing on restricted/private property.
-- See docs/land_verification.md (generated by scripts/verification-checklist.mjs).

ALTER TABLE support_nodes ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'pending'
  CHECK (verification_status IN ('pending', 'verified', 'flagged'));
ALTER TABLE support_nodes ADD COLUMN IF NOT EXISTS verified_note TEXT;
ALTER TABLE support_nodes ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;

ALTER TABLE watchtowers ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'pending'
  CHECK (verification_status IN ('pending', 'verified', 'flagged'));
ALTER TABLE watchtowers ADD COLUMN IF NOT EXISTS verified_note TEXT;
ALTER TABLE watchtowers ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ;
