/**
 * build.js · runs during Vercel build to inject environment variables
 * into js/env.js.
 *
 * In Vercel Dashboard → Settings → Environment Variables, set:
 *   SUPABASE_URL        = https://your-project-id.supabase.co
 *   SUPABASE_ANON_KEY   = eyJhbGci...
 *
 * For local dev: js/env.js is trackable and should contain only public
 * Supabase anon/dev-safe values.
 */

const fs   = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL      || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!url || !key) {
  console.warn('[build] SUPABASE_URL or SUPABASE_ANON_KEY not set · keeping tracked js/env.js as-is.');
  process.exit(0);
}

// Escape single quotes to prevent injection into the JS string literal
const safe = s => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

fs.writeFileSync(
  path.join(__dirname, 'js', 'env.js'),
  `// Auto-generated by build.js at deploy time · DO NOT EDIT.\nwindow.ENV = {\n  SUPABASE_URL:      '${safe(url)}',\n  SUPABASE_ANON_KEY: '${safe(key)}',\n};\n`,
  'utf8'
);

console.log('[build] js/env.js generated from environment variables.');
