/**
 * build.js — runs during Vercel build to inject environment variables
 * into js/env.js (which is gitignored and never committed).
 *
 * In Vercel Dashboard → Settings → Environment Variables, set:
 *   SUPABASE_URL        = https://your-project-id.supabase.co
 *   SUPABASE_ANON_KEY   = eyJhbGci...
 *
 * For local dev: copy js/env.example.js → js/env.js and fill it in manually.
 */

const fs   = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL      || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!url || !key) {
  console.error('[build] ERROR: SUPABASE_URL or SUPABASE_ANON_KEY is not set.');
  console.error('[build] Add them in Vercel → Settings → Environment Variables.');
  // Write a placeholder that makes the error visible in the browser console
  fs.writeFileSync(
    path.join(__dirname, 'js', 'env.js'),
    `window.ENV = { SUPABASE_URL: '', SUPABASE_ANON_KEY: '' };
console.error('[Tamroi] Supabase env vars missing — check Vercel settings.');\n`,
    'utf8'
  );
  process.exit(0); // don't fail the build; app will show config errors at runtime
}

// Escape single quotes to prevent injection into the JS string literal
const safe = s => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

fs.writeFileSync(
  path.join(__dirname, 'js', 'env.js'),
  `// Auto-generated by build.js at deploy time — DO NOT EDIT or commit.\nwindow.ENV = {\n  SUPABASE_URL:      '${safe(url)}',\n  SUPABASE_ANON_KEY: '${safe(key)}',\n};\n`,
  'utf8'
);

console.log('[build] js/env.js generated from environment variables.');
